import type { NextPage } from 'next';
import Head from 'next/head';
import { useTheme } from 'next-themes';
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { gsap } from 'gsap';
import Navbar from '../components/Navbar';
import useCustomCursor from '../hooks/useCustomCursor';
import CustomCursor from '../components/CustomCursor';
import Script from 'next/script';
import useIsMobile from '../hooks/useIsMobile';

const Home: NextPage = () => {
    const { theme, setTheme, themes } = useTheme();
    const parent = useRef(null);
    const isMobile = useIsMobile();

    return (
        <div ref={parent}>
            {isMobile ? <></> : <CustomCursor fade={true} dotSpeed={3} circleSpeed={20}></CustomCursor>}
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="" />
            </Head>

            <Navbar></Navbar>
        </div>
    );
};

export default Home;
