import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/pages/Home.module.css';
import Link from 'next/link';
import { useTheme } from 'next-themes';
import { useState } from 'react';

const Home: NextPage = () => {
    const { theme, setTheme, themes } = useTheme();
    console.log(themes);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="" />
            </Head>

            <main className={styles.main}>
                <button
                    onClick={() => {
                        const randomTheme = themes[Math.floor(Math.random() * themes.length)];
                        setTheme(randomTheme);
                        console.log(randomTheme);
                    }}
                >
                    Change Theme
                </button>
            </main>
        </div>
    );
};

export default Home;
